### ISSUE TITLE
150 Gems Doesn't Activate

### ISSUE THREAD

**Issue by PeterDCarter** [ardaozkal/Rickroll-Wifi#1]
Attempting to activate Wi-Fi results in strange message about spammers that makes no sense. Is this coming from your app? If so, why is it spamming people? Or is the name and profile pic just to stop people noticing what you're doing...

**Comment by ardaozkal** [comment]
seriously dude fuck off

**Comment by ardaozkal** [comment]
stop fucking googling me

**Comment by ardaozkal** [comment]
if you have a problem with fucking stack, goddamn open a meta

**Comment by ardaozkal** [comment]
Context: The user is spamming http://gaming.stackexchange.com and I made them aware that they are wrong, they decided to target my github. He posted these before:


![5xga](https://cloud.githubusercontent.com/assets/6755762/15993696/be7d42cc-30f6-11e6-9192-d0cb283dca00.png)

**Comment by ardaozkal** [comment]
![ffs](https://cloud.githubusercontent.com/assets/6755762/15993713/190c2884-30f7-11e6-83e8-3544d7587010.png)

**Comment by PeterDCarter** [comment]
Context. I was banned from the entire Stack Exchange site to stop me talking to people during the election period. Your Github is linked directly from your profile page.

**Comment by ardaozkal** [comment]
What did you say about the nominees?

**Comment by ardaozkal** [comment]
Also [I know that you are banned](http://chat.stackexchange.com/transcript/message/30311494#30311494).

**Comment by PeterDCarter** [comment]
You were in the chat. You should know.

**Comment by ardaozkal** [comment]
I wasn't.

**Comment by PeterDCarter** [comment]
You were.

**Comment by ardaozkal** [comment]
I was sleeping or working. I can't remember why you got banned.

**Comment by ardaozkal** [comment]
I have a life other than The Bridge, you know.

**Comment by PeterDCarter** [comment]
Convenient. No-one seems to. Odd. My only life it to try to help others. Some fights are important.

**Comment by ardaozkal** [comment]
What exactly did you do?

**Comment by PeterDCarter** [comment]
I'll see if the meta post is still there... just a minute. It was deleted, but I might have a screenshot.

**Comment by ardaozkal** [comment]
J-just add me on steam. I don't want mails of everything you say. http://ardao.me/steam

**Comment by PeterDCarter** [comment]
![image](https://cloud.githubusercontent.com/assets/17948944/15993764/05ce7d30-30e8-11e6-85ea-c70c9c8a1863.png)

**Comment by ardaozkal** [comment]
Your reasoning does not make much sense. Chatrooms are separated because the sites have separate domains. Connecting that with political reasons seems weird.

**Comment by PeterDCarter** [comment]
Yet somehow immediately afterward I was banned from the entire network.

**Comment by ardaozkal** [comment]
Why didn't you just appeal for your ban with http://stackoverflow.com/contact ? By spamming you pmuch lost your chance to tho.

**Comment by ardaozkal** [comment]
@BradLarson locked your post. He is a moderator. He can't ban you network-wide.

**Comment by ardaozkal** [comment]
You were either banned by an employee or community moderator. I guess you offended some people.

**Comment by ardaozkal** [comment]
I'm locking this.
