### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ayyucedemirbas** [ardaozkal/Rickroll-Wifi#2]
![rickoll](https://cloud.githubusercontent.com/assets/8023150/19663913/eb879e66-9a46-11e6-9603-c689475e769e.png)
I got this error message.

**Comment by aveao** [comment]
This is a problem on your end, as you didn't completely install the esp8266 tools.

Go to "C:/Users/ay-_-/AppData/Local/Arduino15/packages/esp8266/tools" and run the python script called "get.py".

If the script isn't there, you can download it from https://github.com/esp8266/Arduino/tree/master/tools
